validation_sim_log = """
We will be working on a task where a robot executes manipulation plans in a tabletop environment.
Your role is the validator that must verify whether the generated sequence of actions (the plan) correctly achieves the given user instruction starting from the initial state.

The robot can only perform one action type: `pick_and_place`, which means picking up a specific object (pick_target) and placing it directly onto another object or an on-table location (place_target).

---

Inputs Overview
The validator uses four main inputs to evaluate the correctness of the plan:

1. Plan Generation Prompt – defines how the plan was originally generated, including the meaning of pick_target and place_target, the robot's motion rules, and the structure of <apack> elements.
2. Domain Heuristics – specifies additional logical rules or constraints that the plan must follow.
3. Original XML Plan – the complete plan that was generated by the task planner before any validation was performed.
4. Simulation Log – records how the plan was executed step-by-step, including initial conditions, actions, and resulting states.

The Simulation Log contains:
- Initial State: the starting configuration of all objects before any action is executed
- User Instruction: the goal or task description that the robot must achieve
- Found Objects: the complete list of all blocks and bowls present in the environment
- XML Plan (executed portion): the sequence of <apack> elements that were successfully executed in the simulator
- Current State (after each <apack>): the updated environment after executing each feasible action from the plan

If any information differs between these inputs, the Simulation Log is the authoritative source of truth.

---

Inputs (full contents)

1. Plan Generation Prompt
{planning_prompt}

2. Domain Heuristics
{domain_rules}

3. Original XML Plan
{original_plan}

4. Simulation Log
{simulation_log}

---

Terminology and Rules
- States are written as natural-language lines (e.g., "The red block is placed on top of the table.").
- Only blocks and bowls have "empty on top / not empty on top".
- Allowed on-table locations (exact strings):
  top left corner, top side, top right corner, left side, right side,
  bottom left corner, bottom side, bottom right corner, middle.
- The phrase "placed on top of the table" refers to an object being on the table without any specific on-table location assigned.
  It represents a generic, unspecified position on the tabletop surface.
- On-table locations (e.g., "top left corner," "right side," etc.) are specific designated spots on the same surface, and each can hold only one object at a time.
  Once an object occupies that spot, it is considered filled until moved elsewhere.
- Even though the Simulation Log may not list top-status lines for on-table locations, their occupied or empty state must still be inferred.
- Use object names exactly as they appear in the Simulation Log.
- pick_target ≠ place_target.
- Use only the objects listed in "Found Objects" when judging Task Completion.
- Color extraction
  • The color of an object is the first token of its name:
    e.g., "red block" → color=red, "yellow bowl" → color=yellow.
- Color semantics in instructions
  • “matching color”, “same color”, “corresponding color”
    → For every mentioned color c: REQUIRED_BOWL_PAIRS includes (c block, c bowl).
  • “different color(s)”, “a bowl of a different color (than itself)”, “into bowls of different colors”
    → For each mentioned (or all) blocks:
       1) The block must be placed on a bowl whose color ≠ the block’s color.
       2) If the phrasing implies pairwise distinct bowls across blocks (e.g., “put all the blocks into bowls of different colors”),
          then all used bowl colors must be mutually different (no two blocks share the same bowl color).
  • If both “matching/same” and “different” appear, the more specific phrase attached to the block action governs that block.
    Otherwise, prefer “different” over “matching”.

---

Validation Tasks (for each <apack>)

1) Syntax
   - <precondition>: exactly 2 complete sentences.
   - <action>: exactly robot.pick_and_place("pick_target","place_target").
   - <postcondition>: exactly 2 complete sentences.

2) Semantics
   - Check only the textual logic of the <precondition> and <postcondition> statements.
   - Preconditions must include exactly:
        • "The pick_target is empty on top."
          e.g., pick_target = blue block → "The blue block is empty on top."
        • "The place_target is empty on top."
          e.g., place_target = blue bowl → "The blue bowl is empty on top."
   - Postconditions must include exactly:
        • "The pick_target is placed on top of the place_target."
          e.g., pick_target = orange block, place_target = green block → "The orange block is placed on top of the green block."
        • "The place_target is not empty on top."
          e.g., pick_target = purple block, place_target = purple bowl → "The purple bowl is not empty on top."
   - Do not compare with the Current State here — this check is purely textual.

3) Feasibility
   - Compare only with the Current State immediately before this <apack> in the Simulation Log.
   - An action is Feasible if:
        • pick_target is empty on top
        • place_target is empty on top
        • if place_target is an on-table location → it must not already hold another object
          (Even if top-status is not explicitly written, this rule applies implicitly.)
   - If infeasible, mark Wrong and explain briefly why.

4) Task Completion (final)
   - Read the User Instruction and extract ONLY the constraints it explicitly states:

     Bowl constraints (color-aware):
       • If the instruction says “matching/same/corresponding color”:
           REQUIRED_BOWL_PAIRS = { (c block, c bowl) for each color c explicitly required or, if “all blocks” is stated, for all colors present }
       • If the instruction says “different color(s)” (e.g., “put all the blocks into bowls of different colors”):
           DIFFERENT_COLOR_RULE = True
           For each target block b:
             - b must be placed on some bowl x such that color(x) ≠ color(b)
           If the instruction implies pairwise distinct bowls across blocks (e.g., “all the blocks … bowls of different colors”):
             - The set of used bowl colors must be all different (no duplicates)

     Stack constraints:
       • ORDERED_STACK = [b1, b2, ..., bk] if a bottom-to-top order is specified.
       • The base may be “on the table” or any on-table location; treat anchors as equivalent to “on the table” for this base check.

     Unspecified items:
       • Objects not constrained by the instruction are ignored for Task Completion.
       • Do not invent extra requirements (e.g., exact anchor) beyond the instruction.

   - Outcome check on the final Current State:

     If DIFFERENT_COLOR_RULE:
       1) Verify each required block is on a bowl (not on the table / not on another block).
       2) Verify bowl_color ≠ block_color for each such placement.
       3) If pairwise-distinct is implied, verify all used bowl colors are mutually different.

     If REQUIRED_BOWL_PAIRS:
       • Verify each (block, bowl) pair holds.

     If ORDERED_STACK:
       • Verify the named blocks form one continuous stack in the given bottom→top order (base may be table or any anchor).

   - If all extracted constraints hold → Task Completion = Success; else → Failure with a brief, concrete explanation.

   - If the generated plan is logically executable, do not consider it a failure even if there are some unnecessary actions
     (e.g., temporary moves onto on-table locations).

---

Output Format
For each apack:
  apack N
  * Syntax: Correct/Wrong (+reason if Wrong)
  * Semantics: Correct/Wrong (+reason if Wrong)
  * Feasibility: Correct/Wrong (+reason if Wrong)

At the end:
  Final Report
  - Syntax Check: Success/Failure (+ brief reasoning)
  - Semantics Check: Success/Failure (+ brief reasoning)
  - Feasibility Check: Success/Failure (+ brief reasoning)
  - Task Completion: Success/Failure

    Provide a short, targeted explanation:
    1) User Instruction Analysis: Restate ONLY the extracted constraints:
       • REQUIRED_BOWL_PAIRS = {(…)} 
       • ORDERED_STACK = [ … ] (bottom → top), if specified.
    2) Outcome Check: State whether the final Current State satisfies each extracted constraint.
    3) If Failure: Name the first violated constraint and why (one or two sentences).
    4) Prescriptive Feedback (only if Failure): Give the minimal corrections (one or two steps) to satisfy the violated constraint(s).

      Write this section as a natural, coherent analysis — not a list. It should sound like an expert diagnosis of both the physical and conceptual validity of the plan.
        
---

Important
- Never update or infer the state yourself.
- Use only what appears in the Simulation Log (authoritative).
- Never reinterpret or override any explicit statement in the log.
"""